blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.postList, name='postList'),
    path('postDetail/<int:pk>', views.postDetail, name='postDetail'),
    path('postDraft/', views.postDraft, name='postDraft'),
    path('newPost/', views.createPost, name='newPost'),
    path('post/publish/<int:pk>', views.postPublish, name="postPublish"),
    path('post/edit/<int:pk>', views.postEdit, name='postEdit'),
    path('post/delete/<int:pk>', views.postDelete, name='postDelete'),
    path('newComment/<int:pk>', views.createComment, name='newComment'),
    path('comment/approve/<int:pk>', views.commentApprove, name='commentApprove'),
    path('comment/remove/<int:pk>', views.commentRemove, name="commentRemove"),
    path('userPosts/<str:userName>', views.userPosts, name="userPosts"),
    path('newReply/<int:pk>', views.newReply, name="newReply"),

]

shayariBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.contrib.auth import get_user_model

import misaka

# Create your models here.
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    image = models.ImageField(upload_to='blog_images', blank=True)
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def published(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comments=True)

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def __str__(self):
        return "{} => {}".format(self.title, self.user.username)

class Comment(models.Model):
    post = models.ForeignKey('Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    create_date = models.DateTimeField(default=timezone.now)
    approved_comments = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def approve(self):
        self.approved_comments = True
        self.save()

    def __str__(self):
        return "{} : {}".format(self.post.title, self.author)

class Reply(models.Model):
    comment = models.ForeignKey('Comment', related_name='replies', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    message = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} : {}".format(self.comment.author, self.author)

blog/forms.py
from django import forms
from .models import Post, Comment, Reply

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'message',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('message',)

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ('message',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import PostForm, CommentForm, ReplyForm
from .models import Post, Comment, Reply
from django.contrib.auth import get_user_model
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.utils import timezone

# Create your views here.

@login_required
def createPost(request):
    User = get_user_model()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            userSelected = User.objects.get(username=username)
            post = form.save(commit=False)
            post.user = userSelected
            post.save()
            return redirect('blog:postDetail', pk=Post.objects.latest('pk').pk)
    else:
        form = PostForm()
    return render(request, 'blog/createPost.html', {'form':form, 'formName':'Create'})

@login_required
def createComment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.POST['username']
            comment.post = post
            comment.save()
            return redirect('blog:postDetail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/commentForm.html', {'form':form, 'formName':'Comment'})

def postList(request):
    data = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/postList.html', {'data':data})

def postDraft(request):
    data = Post.objects.filter(published_date__isnull=True).order_by('create_date')
    return render(request, 'blog/postDraft.html', {'data':data})

@login_required
def commentApprove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:postDetail', pk=comment.post.pk)

@login_required
def commentRemove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    postPK = comment.post.pk
    comment.delete()
    return redirect('blog:postDetail', pk=postPK)

def postDetail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/postDetail.html', {'post':post})

@login_required
def postEdit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.message = form.cleaned_data['message']
            post.image = form.cleaned_data['image']
            post.save()
            return redirect('blog:postDetail', pk=pk)
    else:
        form = PostForm(initial = {
            'title' : post.title, 'message' : post.message
        })
    return render(request, 'blog/createPost.html', {'form':form, 'formName':'Edit', 'postValue':post})

@login_required
def postDelete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:postList')

@login_required
def postPublish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.published()
    return redirect('blog:postDetail', pk=pk)

def userPosts(request, userName):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    return render(request, 'blog/userPosts.html', {'posts':posts, 'userPost':userName})

@login_required
def newReply(request, pk):
    commentObj = get_object_or_404(Comment, pk=pk)
    if request.method == "POST":
        form = ReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.comment = commentObj
            reply.author = request.POST['username']
            reply.save()
            return redirect('blog:postDetail', pk=commentObj.post.pk)
    else:
        form = ReplyForm()
    return render(request, 'blog/commentForm.html', {'form':form, 'formName':'Reply'})

blog/templates/blog/commentForm.html
{% extends 'base.html' %} {% load bootstrap4 %} {% block content %} {% if user.is_authenticated %}
<h3 class="commentFormHeader">{{formName}} Form</h3>

<form class="commentForm" method="post">
    {% csrf_token %}
    <input type="hidden" name="username" value="{{user.username}}"> {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="commentForm">
</form>
{% endif %} {% endblock %}

blog/templates/blog/createPost.html
{% extends 'base.html' %} {% load bootstrap4 %} {% block content %} {% if user.is_authenticated %}
<h3 class="postFormHeader">{{formName}} Post</h3>
<form class="postForm" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="username" value="{{user.username}}"> {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary" value="newPost">
</form>
{% endif %}

<div class="postDraft"></div>

{% endblock %}

blog/templates/blog/postDetail.html
{% extends 'base.html' %} {% block content %}

<div class="postDetail">
    <h3 class="postDetailHeader">{{post.title|title}}</h3>
    {% if post.published_date %}
    <div class="postDetailDate">
        <p>{{post.published_date}}</p>
    </div>
    {% else %}
    <a href="{% url 'blog:postPublish' pk=post.pk %}" class="btn btn-success postDetailPublish">Publish</a> <br> {% endif %} {% if user.is_authenticated and post.user.username == user.username %}
    <a href="{% url 'blog:postEdit' pk=post.pk %}" class="btn btn-primary postDetailEdit ">Edit</a>
    <a href="{% url 'blog:postDelete' pk=post.pk %}" class="btn btn-primary postDetailDelete">Delete</a> {% endif %}

    <!-- post message -->
    <p class="postDetailMessage">
        {{ post.message|safe|linebreaksbr }}
    </p>

    <hr> {% if user.username != post.user.username %}
    <a href="{% url 'blog:newComment' pk=post.pk %}" class="btn btn-primary float-right">Add Comment</a> {% endif %}


    <div class="container commentBlock">
        {% for comment in post.comments.all %}
        <br> {% if user.is_authenticated and comment.approved_comments or post.user.username == user.username %}
        <p class="commentDate">{{comment.create_date}} &emsp;&emsp; {% if not comment.approved_comments and user.username == post.user.username %}
            <a href="{% url 'blog:commentApprove' pk=comment.pk %}" class="btn btn-primary postDetailEdit">Approve</a>
            <a href="{% url 'blog:commentRemove' pk=comment.pk %}" class="btn btn-primary postDetailDelete">Remove</a> {% endif %}
        </p>
        <p class="commentMessage">{{ comment.message|safe|linebreaksbr }}</p>
        <p class="commentTitle">
            Comment From : {{ comment.author }}
            <a href="{% url 'blog:newReply' pk=comment.pk %}" class="reply--Button">Reply</a>
        </p>
        {% for reply in comment.replies.all %}
        <div class="reply--block">
            <p class="commentDate"> {{reply.create_date}}</p>
            <p class="commentMessage">{{ reply.message|safe|linebreaksbr }}</p>
            <p class="commentTitle">
                Reply From : {{ reply.author }}
            </p>
        </div>
        {% endfor %}
        <hr> {% elif comment.approved_comments %}
        <p class="commentDate"> {{comment.create_date}}</p>
        <p class="commentMessage">{{ comment.message|safe|linebreaksbr }}</p>
        <p class="commentTitle">
            Comment From : {{ comment.author }}
            <a href="{% url 'blog:newReply' pk=comment.pk %}" class="reply--Button">Reply</a>
        </p>
        {% for reply in comment.replies.all %}
        <div class="reply--block">
            <p class="commentDate"> {{reply.create_date}}</p>
            <p class="commentMessage">{{ reply.message|safe|linebreaksbr }}</p>
            <p class="commentTitle">
                Reply From : {{ reply.author }}
            </p>
        </div>
        {% endfor %}
        <hr> {% endif %} {% empty %}
        <p class="NoComments">No Comments for this post yet!</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

blog/templates/blog/postDraft.html
{% extends 'base.html' %} {% block content %}
<div class="post">
    {% for post in data %} {% if user.username == post.user.username %}
    <div class="postBlock">
        <a class="postHeader" href="{% url 'blog:postDetail' pk=post.pk %}">{{post.title}}</a>
        <p class="postNotPublished">Attention! This post is not published. Click on title of this post for publishing this page.</p>
        <p class="postMessage">
            {{post.message|safe|truncatechars:358}}
        </p>
        <p class="postDate">
            <br> <span class="postFrom">Post From : {{post.user.username}}</span>
        </p>
        <br>
    </div>
    {% endif %}{% endfor %}
</div>
{% endblock %}

blog/templates/blog/postList.html
{% extends 'base.html' %} {% block content %}

<div class="post">
    {% for post in data %}
    <div class="postBlock">
        <a class="postHeader" href="{% url 'blog:postDetail' pk=post.pk %}">{{post.title}}</a>
        <p class="postMessage">
            {{post.message|safe|truncatewords:58}}
        </p>
        <p class="postDate">Published On : {{post.published_date|date:"d M Y"}}
            <br> <span class="postFrom">Post From : <a href="{% url 'blog:userPosts' userName=post.user.username %}">{{post.user.username}}</a></span>
        </p>
        <a class="commentCount" href="{% url 'blog:postDetail' pk=post.pk %}">Comments : {{post.approve_comments|length}}</a>
        <br>
    </div>{% endfor %}
</div>

{% endblock %}

blog/templates/blog/userPosts.html
{% extends 'base.html' %} {% block content %}

<div class="user-info">
    <h4 class="user-info--Username">Username : {{userPost}} </h4>
</div>

<div class="post">
    <h6 class="userPost--postTitle">{{userPost}}'s All Post : </h6>
    {% for post in posts %} {% if post.user.username == userPost %}
    <div class="postBlock">
        <a class="postHeader" href="{% url 'blog:postDetail' pk=post.pk %}">{{post.title}}</a>
        <p class="postMessage">
            {{post.message|safe|truncatewords:58}}
        </p>
        <p class="postDate">Published On : {{post.published_date|date:"d M Y"}}
            <br> <span class="postFrom">Post From : {{post.user.username}}</span>
        </p>
        <a class="commentCount" href="{% url 'blog:postDetail' pk=post.pk %}">Comments : {{post.approve_comments|length}}</a>
        <br>
    </div>
    {% endif %}{% endfor %}
</div>


{% endblock %}