accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

from . import views

app_name = "accounts"

urlpatterns = [
    path('signUp/', views.SignUp.as_view(), name='signUp'),
    path('login/', auth_view.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.postList, name='postList'),
    path('postDetail/<int:pk>', views.postDetail, name='postDetail'),
    path('postDraft/', views.postDraft, name='postDraft'),
    path('newPost/', views.createPost, name='newPost'),
    path('post/publish/<int:pk>', views.postPublish, name="postPublish"),
    path('post/edit/<int:pk>', views.postEdit, name='postEdit'),
    path('post/delete/<int:pk>', views.postDelete, name='postDelete'),
    path('newComment/<int:pk>', views.createComment, name='newComment'),
    path('comment/approve/<int:pk>', views.commentApprove, name='commentApprove'),
    path('comment/remove/<int:pk>', views.commentRemove, name="commentRemove"),
    path('userPosts/<str:userName>', views.userPosts, name="userPosts"),
    path('newReply/<int:pk>', views.newReply, name="newReply"),

]

shayariBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shayari Blog</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/cerulean/bootstrap.min.css" integrity="sha384-b+jboW/YIpW2ZZYyYdXczKK6igHlnkPNfN9kYAbqYV7rNQ9PKTXlS2D6j1QZIATW" crossorigin="anonymous">

    <!-- Custom css -->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Fondamento&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat" rel="stylesheet">

    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
</head>

<body>
    <div class="bgImage"> </div>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'home' %}"> <span class="navbar-brand-logo"><i class="ri-stack-fill" style="vertical-align: middle;"></i> Anyone's Blog</span> </a>

        <div class="collapse navbar-collapse navbar-headers" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'blog:postList' %}">Blogs</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'blog:userPosts' userName=user.username %}">My Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'blog:postDraft' %}">Draft</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'blog:newPost' %}">New Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navLinkFont active navbar-text"> Welcome: {{ user.username }}</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'accounts:login' %}?next={{ request.path|urlencode }} ">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navLinkFont navbar-text" href="{% url 'accounts:signUp' %}">SignUp</a>
                </li>
                {% endif %}
            </ul>

            <!-- Search button 
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
            -->
        </div>
    </nav>

    <!-- Content block -->
    <div class="container mainBlockContainer">
        {% block content %}{% endblock %}
    </div>
</body>

</html>

templates/index.html
{% extends 'base.html' %} {% block content %}

<div class="landing--section">
    <div class="image--holder"></div>
    <h2 class="homePageTitle">Welcome to, <br> Anyone's blog</h2>
</div>

<div class="working-section">
    <h2 class="working-section--title">Blog's Features</h2>
    <div class="working-section--container">
        <div class="working-section--image-container">
            <img src="/media/undraw_browsing_online_sr8c.png" class="working-section--image" alt="">
        </div>
        <div class="working-section--description">
            <h4>User can browse different posts</h4>
        </div>
    </div>
    <div class="working-section--container">
        <div class="working-section--image-container">
            <img src="/media/undraw_my_documents_ym8x.png" class="working-section--image" alt="">
        </div>
        <div class="working-section--description">
            <h4>User can see posts related to specific user</h4>
        </div>
    </div>
    <div class="working-section--container">
        <div class="working-section--image-container">
            <img src="/media/undraw_save_to_bookmarks_y708.png" class="working-section--image" alt="">
        </div>
        <div class="working-section--description">
            <h4>Posts can also be saved as drafts</h4>
        </div>
    </div>
    <div class="working-section--container">
        <div class="working-section--image-container">
            <img src="/media/undraw_shared_goals_3d12.png" class="working-section--image" alt="">
        </div>
        <div class="working-section--description">
            <h4>User can comment and reply on different posts</h4>
        </div>
    </div>
</div>

{% endblock %}